services:
  ## PostgreSQL Database Server with Vector
  pgvectordb:
    image: pgvector/pgvector:pg17
    container_name: pgvectordb
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    networks:
      - reverseproxy
    volumes:
      - "/root/data/pgvector:/var/lib/postgresql/data"
    restart: always
  ## pgAdmin 4 Service
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: 
      PGADMIN_DEFAULT_PASSWORD: 
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - "/root/data/pgadmin:/var/lib/pgadmin"
    networks:
      - reverseproxy
    ports:
      - '8081:80'
    depends_on:
      - pgvectordb

networks:
  reverseproxy:
    external: true
    name: reverseproxy